export const EDIT_ENTITY = 'EDIT_ENTITY';
export const ADD_ENTITY = 'ADD_ENTITY';
export const GET_ENTITY = 'GET_ENTITY';
export const CLOSE_ENTITY_PANEL = 'CLOSE_ENTITY_PANEL';
export const SET_RELATED_ENTITY = 'SET_RELATED_ENTITY';
export const SHOW_ENTITY_PANEL = 'SHOW_ENTITY_PANEL';
export const CANCEL_ENTITY_PANEL_OPERATION = 'CANCEL_ENTITY_PANEL_OPERATION';
export const CHANGE_RELATED_ENTITIES = 'CHANGE_RELATED_ENTITIES';