export const SHOW_SUCCESS_MESSAGE_BOX= 'SHOW_SUCCESS_MESSAGE_BOX';
export const SHOW_FAIL_MESSAGE_BOX= 'SHOW_FAIL_MESSAGE_BOX';
export const SHOW_ERROR_MESSAGE_BOX= 'SHOW_NETWORK_ERROR_MESSAGE_BOX';
export const HIDE_MESSAGE_BOX= 'HIDE_MESSAGE_BOX';