export const CHECK_PREVIOUSLY_CHECKED_ELEMENTS = 'CHECK_PREVIOUSLY_CHECKED_ELEMENTS';
export const SET_EMPTY_PAGE = 'SET_EMPTY_PAGE';
export const CHECK_ALL_ELEMENTS = 'CHECK_ALL_ELEMENTS';
export const CHECK_ELEMENTS = 'CHECK_ELEMENTS';
export const CHECK_ELEMENT = 'CHECK_ELEMENT';
export const CLEAR_CHECKED_ELEMENTS = 'CLEAR_CHECKED_ELEMENTS';
export const SET_ELEMENTS_TO_CHECK = 'SET_ELEMENTS_TO_CHECK';